version: '3.8'
services:
  app:
    container_name: journalapi
    build:
      context: .
      args:
        - JWT_SECRET=super_secret
        - DATABASE_URL="postgresql://postgres:123@journalapi:5434/journal?schema=public"
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    depends_on:
      - database
    env_file:
      - .env
  db:
    image: postgres:13
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: journal
  
  test-db:
    image: postgres:13
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: journal

