version: '3.8'
services:
  app:
    build:
      context: .
      # args:
      #   -POSTGRES_PWD=123
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
  db:
    image: postgres:13
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: journal
  
  test-db:
    image: postgres:13
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: journal

